# Render.com deployment configuration
# This file helps with deployment settings

# Build settings
build_command: ""
publish_directory: "."
environment: "static"

# Headers for security and performance
headers:
  /*:
    - "X-Frame-Options: DENY"
    - "X-Content-Type-Options: nosniff"
    - "X-XSS-Protection: 1; mode=block"
    - "Referrer-Policy: strict-origin-when-cross-origin"
    - "Permissions-Policy: geolocation=(), microphone=(), camera=()"
  
  *.css:
    - "Cache-Control: public, max-age=31536000, immutable"
  
  *.js:
    - "Cache-Control: public, max-age=31536000, immutable"
  
  *.png:
    - "Cache-Control: public, max-age=31536000, immutable"
  
  *.jpg:
    - "Cache-Control: public, max-age=31536000, immutable"
  
  *.svg:
    - "Cache-Control: public, max-age=31536000, immutable"

# Redirects
redirects:
  - from: "/www/*"
    to: "/:splat"
    status: 301
    force: true

# Custom error pages
error_pages:
  404: "/404.html"
  500: "/500.html"
